project:
  type: website
  output-dir: "docs"

website:
  title: "Analytic Design Theory"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: faq.qmd
        text: FAQ
      - text: "More Info"
        menu: 
          - href: talks.qmd
            text: Talks
          - href: about.qmd
            text: About
          - href: jobs.qmd
            text: Jobs


format:
  html:
    theme: litera
    css: styles.css
    toc: true



