project:
  type: website
  output-dir: "docs"

website:
  title: "Theory of Data Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - contributors.qmd
      - publications.qmd
      - href: talks.qmd
        text: Talks
      - jobs.qmd


format:
  html:
    theme: litera
    css: styles.css
    toc: true



