project:
  type: website
  output-dir: "docs"

website:
  title: "Theory of Data Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



