---
title: "About"
---

# History 

Add more here about the early days of data analysis research (e.g. tukey, etc). 

Analytic Design Theory (ADT) was formally established as a distinct scientific discpline in 2023 by [Lucy D'Agostino McGowan](https://www.lucymcgowan.com), [Stephanie Hicks](https://www.stephaniehicks.com), and [Roger Peng](https://rdpeng.org). The three individuals gathered at Wake Forest University in Winston-Salem, North Carolina in the USA for a four day inaugural meeting on October 16-19, 2023. A panel session with Roger and Stephanie as panelists and Lucy as a moderator was held on October 17th where research topics in the field were introduced and discussed.

Prior to this 2023 meeting, the foundations and underpinnings of this field were being established as far back as 2018 with both [Stephanie Hicks](https://www.stephaniehicks.com) and [Roger Peng](https://rdpeng.org) at Johns Hopkins University with [early works](publications.qmd) as of 2018. 

Today, the field... 