---
title: "Contributors"
---

## Faculty

**Stephanie Hicks** is an Associate Professor in the Department of Biostatistics at Johns Hopkins University and is an applied statistician working at the intersection of genomics and biomedical data science. Her research addresses statistical and computational challenges in single-cell genomics, epigenomics, and spatial transcriptomics leading to an improved understanding of human health and disease. Specifically, she develops fast and scalable [computational methods](https://www.stephaniehicks.com/projects.html) and [open-source software](https://www.stephaniehicks.com/software.html) for biomedical data analysis.Her research philosophy is [problem-forward](https://simplystatistics.org/posts/2013-05-29-what-statistics-should-do-about-big-data-problem-forward-not-solution-backward/): she develops computational methods and software that are motivated by concrete problems, often with real-world, messy data. This philosophy permeates into her contributions to statistics and data science [education](https://www.stephaniehicks.com/teaching.html), and service to the profession including being an advocate for diversity, equity, and inclusion. Dr. Hicks is ia co-host of the [The Corresponding Author](https://twitter.com/CorrespondAuth) podcast, member of the [Editorial Board for *Genome Biology*](https://genomebiology.biomedcentral.com/about/editorial-board), an Associate Editor for [Reproducibility](https://jasa-acs.github.io/repro-guide/) at the [*Journal of the American Statistical Association*](https://www.tandfonline.com/toc/uasa20/current), and co-founder of [R-Ladies Baltimore](https://www.meetup.com/rladies-baltimore/). She is the recipient of the [Myrto Lefkopoulou Distinguished Lectureship](https://www.hsph.harvard.edu/biostatistics/myrto-award/) at the Harvard T.H. Chan School of Public Health.

**Lucy D'Agostino McGowan** is an Associate Professor in the Department of Statistical Sciences at Wake Forest University. She received her PhD in Biostatistics from Vanderbilt University and completed her postdoctoral training at Johns Hopkins University Bloomberg School of Public Health. Her research focuses on statistical communication, causal inference, data science pedagogy, and human-data interaction. Dr. D’Agostino McGowan is the 2023 chair of the American Statistical Association’s Section on Statistical Graphics and can be found blogging at [livefreeordichotomize.com](https://livefreeordichotomize.com/), on Twitter [\@LucyStats](https://twitter.com/LucyStats), and podcasting on the American Journal of Epidemiology partner podcast, [Casual Inference](https://casualinfer.libsyn.com/).

**Roger D. Peng** is a Professor of [Statistics and Data Sciences](https://stat.utexas.edu) at the University of Texas, Austin. Previously, he was [Professor of Biostatistics](https://publichealth.jhu.edu/departments/biostatistics) at the Johns Hopkins Bloomberg School of Public Health and the Co-Director of the [Johns Hopkins Data Science Lab](https://jhudatascience.org). His current research focuses on developing theory and methods for building successful data analyses and on the development of statistical methods for addressing environmental health problems. He is the author of the popular book [*R Programming for Data Science*](https://leanpub.com/rprogramming) and 10 other books on data science and statistics. He is also the co-creator of the [Simply Statistics blog](https://simplystatistics.org) where he writes about statistics for the public, the [Not So Standard Deviations podcast](https://nssdeviations.com) with Hilary Parker, and [The Effort Report podcast](https://effortreport.libsyn.com) with Elizabeth Matsui. Roger is a Fellow of the American Statistical Association and is the recipient of the Mortimer Spiegelman Award from the American Public Health Association, which honors a statistician who has made outstanding contributions to public health. Roger received a PhD in Statistics from the University of California, Los Angeles.

