---
title: "Jobs"
editor: source
---


## Postdoctoral Fellowship in Data Science at UT Austin

I have openings for Postdoctoral Fellowships in Data Science at UT Austin. This position provides candidates with the opportunity to conduct research in the theory of data analytic practice and to expand the training of data analysis to large audiences. The goal for this position is to contribute to a foundation of scholarship around data analysis and to translate our research into scalable data science education materials. Projects can cover

* Research: Empirical, methodological, theoretical, or computational investigations into data analysis strategies, techniques, and practice.

* Content Development: Building online and in-person course materials, books, video and audio materials, case studies, and potentially other short-form content for the purpose of wide distribution.

Candidates will join a collegial and interdisciplinary team. Opportunities are also available to interact with a network of collaborators at the [Johns Hopkins Data Science Lab](https://jhudatascience.org), the [Open Case Studies Project](https://www.opencasestudies.org), the [UT Center for Health and Environment: Education and Research (CHEER)](https://dellmed.utexas.edu/units/center-for-health-environment-education-research), and the Fred Hutchinson Cancer Research Center.


### Qualifications

* PhD in statistics, biostatistics, computer science, genomics, bioinformatics, or related data intensive field 
* Experience programming and doing data analysis with R
* Experience teaching hands-on data analysis skills in R (e.g. classroom, workshop, tutorial)
* Excellent communication and task management skills 
* Experience writing papers for peer-reviewed publication


### Application Instructions 

Applicants should submit a cover letter describing their interest in the position, including a brief description of an experience teaching data analysis or any other relevant curriculum. Applicants should also submit a CV and are encouraged to include a link to their GitHub profile, if available. Please e-mail applications to Dr. Roger Peng (roger.peng AT austin.utexas.edu). 
